### ISSUE TITLE
Confusing phrasing

### ISSUE THREAD

**Issue by wjthompson-ntap** [NetAppDocs/bluexp-reports#2]
### Page URL

https://docs.netapp.com/us-en/bluexp-reports/get-started/prerequisites.html

### Page title

BlueXP migration reports prerequisites

### Summary

Unsure what this means in requirements, can this be clarified?

"The BlueXP Connector set up in NetApp BlueXP to the management LIF"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Hello @wjthompson-ntap. Thank you for your comment. I missed this comment and apologize for the delay. Checking with Engineering on this and will get back to you.

**Comment by amgrissino** [comment]
Hello @wjthompson-ntap. Here is more information. The cluster management LIF is a virtual network interface that enables you to perform cluster management operations. To perform cluster management operations via LIF,  you need to BlueXP Connector, Migration reports require this Connector. 
Does this information help?

**Comment by amgrissino** [comment]
@wjthompson-ntap  - I have added this information to the prerequisites and will close this. Let us know if you have additional feedback. Thanks again.

**Comment by amgrissino** [comment]
Closing
